//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="lab7_serviceRef_MSD.WebServicesMultiplatformSoap")]
    public interface WebServicesMultiplatformSoap {
        
        // CODEGEN: Generating message contract since element name GetLanguagesListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLanguagesList", ReplyAction="*")]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListResponse GetLanguagesList(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLanguagesList", ReplyAction="*")]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListResponse> GetLanguagesListAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequest request);
        
        // CODEGEN: Generating message contract since element name lang from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWord", ReplyAction="*")]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordResponse AddWord(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWord", ReplyAction="*")]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordResponse> AddWordAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequest request);
        
        // CODEGEN: Generating message contract since element name lang from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLanguage", ReplyAction="*")]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageResponse AddLanguage(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLanguage", ReplyAction="*")]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageResponse> AddLanguageAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequest request);
        
        // CODEGEN: Generating message contract since element name lang from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWords", ReplyAction="*")]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsResponse GetAllWords(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWords", ReplyAction="*")]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsResponse> GetAllWordsAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterStudent", ReplyAction="*")]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentResponse RegisterStudent(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentResponse> RegisterStudentAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersResponse GetAllUsers(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersResponse> GetAllUsersAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInResponse LogIn(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInResponse> LogInAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNativeLanguage", ReplyAction="*")]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageResponse getNativeLanguage(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNativeLanguage", ReplyAction="*")]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageResponse> getNativeLanguageAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLearningLanguage", ReplyAction="*")]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageResponse getLearningLanguage(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLearningLanguage", ReplyAction="*")]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageResponse> getLearningLanguageAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLanguagesListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLanguagesList", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequestBody Body;
        
        public GetLanguagesListRequest() {
        }
        
        public GetLanguagesListRequest(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLanguagesListRequestBody {
        
        public GetLanguagesListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLanguagesListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLanguagesListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListResponseBody Body;
        
        public GetLanguagesListResponse() {
        }
        
        public GetLanguagesListResponse(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLanguagesListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.ArrayOfAnyType GetLanguagesListResult;
        
        public GetLanguagesListResponseBody() {
        }
        
        public GetLanguagesListResponseBody(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.ArrayOfAnyType GetLanguagesListResult) {
            this.GetLanguagesListResult = GetLanguagesListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddWord", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequestBody Body;
        
        public AddWordRequest() {
        }
        
        public AddWordRequest(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddWordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lang;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string word;
        
        public AddWordRequestBody() {
        }
        
        public AddWordRequestBody(string lang, string word) {
            this.lang = lang;
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddWordResponse", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordResponseBody Body;
        
        public AddWordResponse() {
        }
        
        public AddWordResponse(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddWordResult;
        
        public AddWordResponseBody() {
        }
        
        public AddWordResponseBody(bool AddWordResult) {
            this.AddWordResult = AddWordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLanguage", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequestBody Body;
        
        public AddLanguageRequest() {
        }
        
        public AddLanguageRequest(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddLanguageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lang;
        
        public AddLanguageRequestBody() {
        }
        
        public AddLanguageRequestBody(string lang) {
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLanguageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageResponseBody Body;
        
        public AddLanguageResponse() {
        }
        
        public AddLanguageResponse(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddLanguageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddLanguageResult;
        
        public AddLanguageResponseBody() {
        }
        
        public AddLanguageResponseBody(bool AddLanguageResult) {
            this.AddLanguageResult = AddLanguageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWords", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequestBody Body;
        
        public GetAllWordsRequest() {
        }
        
        public GetAllWordsRequest(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllWordsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lang;
        
        public GetAllWordsRequestBody() {
        }
        
        public GetAllWordsRequestBody(string lang) {
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWordsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsResponseBody Body;
        
        public GetAllWordsResponse() {
        }
        
        public GetAllWordsResponse(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllWordsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.ArrayOfAnyType GetAllWordsResult;
        
        public GetAllWordsResponseBody() {
        }
        
        public GetAllWordsResponseBody(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.ArrayOfAnyType GetAllWordsResult) {
            this.GetAllWordsResult = GetAllWordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterStudent", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequestBody Body;
        
        public RegisterStudentRequest() {
        }
        
        public RegisterStudentRequest(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lang_native;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string lang_learning;
        
        public RegisterStudentRequestBody() {
        }
        
        public RegisterStudentRequestBody(string name, string surname, string lang_native, string lang_learning) {
            this.name = name;
            this.surname = surname;
            this.lang_native = lang_native;
            this.lang_learning = lang_learning;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentResponseBody Body;
        
        public RegisterStudentResponse() {
        }
        
        public RegisterStudentResponse(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterStudentResult;
        
        public RegisterStudentResponseBody() {
        }
        
        public RegisterStudentResponseBody(string RegisterStudentResult) {
            this.RegisterStudentResult = RegisterStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.ArrayOfAnyType GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.ArrayOfAnyType GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(bool LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNativeLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNativeLanguage", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequestBody Body;
        
        public getNativeLanguageRequest() {
        }
        
        public getNativeLanguageRequest(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNativeLanguageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public getNativeLanguageRequestBody() {
        }
        
        public getNativeLanguageRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNativeLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNativeLanguageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageResponseBody Body;
        
        public getNativeLanguageResponse() {
        }
        
        public getNativeLanguageResponse(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNativeLanguageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getNativeLanguageResult;
        
        public getNativeLanguageResponseBody() {
        }
        
        public getNativeLanguageResponseBody(string getNativeLanguageResult) {
            this.getNativeLanguageResult = getNativeLanguageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLearningLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLearningLanguage", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequestBody Body;
        
        public getLearningLanguageRequest() {
        }
        
        public getLearningLanguageRequest(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getLearningLanguageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public getLearningLanguageRequestBody() {
        }
        
        public getLearningLanguageRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLearningLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLearningLanguageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageResponseBody Body;
        
        public getLearningLanguageResponse() {
        }
        
        public getLearningLanguageResponse(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getLearningLanguageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getLearningLanguageResult;
        
        public getLearningLanguageResponseBody() {
        }
        
        public getLearningLanguageResponseBody(string getLearningLanguageResult) {
            this.getLearningLanguageResult = getLearningLanguageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicesMultiplatformSoapChannel : Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicesMultiplatformSoapClient : System.ServiceModel.ClientBase<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap>, Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap {
        
        public WebServicesMultiplatformSoapClient() {
        }
        
        public WebServicesMultiplatformSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicesMultiplatformSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesMultiplatformSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesMultiplatformSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListResponse Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.GetLanguagesList(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequest request) {
            return base.Channel.GetLanguagesList(request);
        }
        
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.ArrayOfAnyType GetLanguagesList() {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequestBody();
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListResponse retVal = ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).GetLanguagesList(inValue);
            return retVal.Body.GetLanguagesListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListResponse> Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.GetLanguagesListAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequest request) {
            return base.Channel.GetLanguagesListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListResponse> GetLanguagesListAsync() {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetLanguagesListRequestBody();
            return ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).GetLanguagesListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordResponse Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.AddWord(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequest request) {
            return base.Channel.AddWord(request);
        }
        
        public bool AddWord(string lang, string word) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequestBody();
            inValue.Body.lang = lang;
            inValue.Body.word = word;
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordResponse retVal = ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).AddWord(inValue);
            return retVal.Body.AddWordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordResponse> Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.AddWordAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequest request) {
            return base.Channel.AddWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordResponse> AddWordAsync(string lang, string word) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddWordRequestBody();
            inValue.Body.lang = lang;
            inValue.Body.word = word;
            return ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).AddWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageResponse Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.AddLanguage(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequest request) {
            return base.Channel.AddLanguage(request);
        }
        
        public bool AddLanguage(string lang) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequestBody();
            inValue.Body.lang = lang;
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageResponse retVal = ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).AddLanguage(inValue);
            return retVal.Body.AddLanguageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageResponse> Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.AddLanguageAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequest request) {
            return base.Channel.AddLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageResponse> AddLanguageAsync(string lang) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.AddLanguageRequestBody();
            inValue.Body.lang = lang;
            return ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).AddLanguageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsResponse Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.GetAllWords(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequest request) {
            return base.Channel.GetAllWords(request);
        }
        
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.ArrayOfAnyType GetAllWords(string lang) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequestBody();
            inValue.Body.lang = lang;
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsResponse retVal = ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).GetAllWords(inValue);
            return retVal.Body.GetAllWordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsResponse> Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.GetAllWordsAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequest request) {
            return base.Channel.GetAllWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsResponse> GetAllWordsAsync(string lang) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllWordsRequestBody();
            inValue.Body.lang = lang;
            return ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).GetAllWordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentResponse Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.RegisterStudent(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequest request) {
            return base.Channel.RegisterStudent(request);
        }
        
        public string RegisterStudent(string name, string surname, string lang_native, string lang_learning) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequestBody();
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.lang_native = lang_native;
            inValue.Body.lang_learning = lang_learning;
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentResponse retVal = ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).RegisterStudent(inValue);
            return retVal.Body.RegisterStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentResponse> Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.RegisterStudentAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequest request) {
            return base.Channel.RegisterStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentResponse> RegisterStudentAsync(string name, string surname, string lang_native, string lang_learning) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.RegisterStudentRequestBody();
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.lang_native = lang_native;
            inValue.Body.lang_learning = lang_learning;
            return ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).RegisterStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersResponse Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.GetAllUsers(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.ArrayOfAnyType GetAllUsers() {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequestBody();
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersResponse retVal = ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersResponse> Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.GetAllUsersAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersResponse> GetAllUsersAsync() {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.GetAllUsersRequestBody();
            return ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).GetAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInResponse Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.LogIn(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public bool LogIn(string username) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequestBody();
            inValue.Body.username = username;
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInResponse retVal = ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).LogIn(inValue);
            return retVal.Body.LogInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInResponse> Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.LogInAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequest request) {
            return base.Channel.LogInAsync(request);
        }
        
        public System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInResponse> LogInAsync(string username) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.LogInRequestBody();
            inValue.Body.username = username;
            return ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).LogInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageResponse Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.getNativeLanguage(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequest request) {
            return base.Channel.getNativeLanguage(request);
        }
        
        public string getNativeLanguage(string username) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequestBody();
            inValue.Body.username = username;
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageResponse retVal = ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).getNativeLanguage(inValue);
            return retVal.Body.getNativeLanguageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageResponse> Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.getNativeLanguageAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequest request) {
            return base.Channel.getNativeLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageResponse> getNativeLanguageAsync(string username) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getNativeLanguageRequestBody();
            inValue.Body.username = username;
            return ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).getNativeLanguageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageResponse Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.getLearningLanguage(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequest request) {
            return base.Channel.getLearningLanguage(request);
        }
        
        public string getLearningLanguage(string username) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequestBody();
            inValue.Body.username = username;
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageResponse retVal = ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).getLearningLanguage(inValue);
            return retVal.Body.getLearningLanguageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageResponse> Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap.getLearningLanguageAsync(Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequest request) {
            return base.Channel.getLearningLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageResponse> getLearningLanguageAsync(string username) {
            Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequest inValue = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequest();
            inValue.Body = new Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.getLearningLanguageRequestBody();
            inValue.Body.username = username;
            return ((Michal_Sitarczuk_Lab7_Client2.lab7_serviceRef_MSD.WebServicesMultiplatformSoap)(this)).getLearningLanguageAsync(inValue);
        }
    }
}
